#define DEFAULTssid "***"
#define DEFAULTpsw "***"
#define MQTTid "esp-pir"
#define MQTTip "1.2.3.4"
#define MQTTport 1883
#define MQTTuser "***"
#define MQTTpsw "***"
#define MQTTpubQos 1
#define MQTTsubQos 1
